### ISSUE TITLE
Specific pretrained word embedding file to use

### ISSUE THREAD

**Issue by titipata** [edvisees/sciDP#3]
Hello @pdasigi, I just have a question on which embedding file that we have to download from 
http://evexdb.org/pmresources/vec-space-models/

Currently, I downloaded `wikipedia-pubmed-and-PMC-w2v.bin` and provide as a path in `--repfile REPFILE`. However, I got the following errors:

```bash
  File "nn_passage_tagger.py", line 106
    raise RuntimeError, "Tagger not trained yet!"
                      ^
SyntaxError: invalid syntax
```

I seems like I don't have the right trained word2vec file in this case.

**Comment by pdasigi** [comment]
@titipata Firstly, sorry for the huge delay in responding to this issue. I had not noticed this earlier because I am not actively developing this project anymore.
FWIW, the choice of embedding depends on your data (I have used the `PMC-w2v.bin` myself). It should work with any embedding. Please also note that you will have to convert the bin files to txt and gzip them first.
Make sure your command line arguments include `--train_data`, without which sciDT assumes you already have a serialized model in the directory. Base on the error message you posted, that seems to be the issue.

**Comment by titipata** [comment]
Thanks @pdasigi and no worry! Yeah, I figured out lately that I have to convert `.bin` file to `.txt` file first. I used `gensim` to do that. I guess I can close this issue. Thanks again 👍
